---
name: E2E

on:
  workflow_call: # yamllint disable-line rule:truthy
    inputs:
      os:
        description: 'Operating system'
        required: true
        type: string
      python-version:
        description: 'Python version'
        required: true
        type: string
      dotnet-version:
        description: '.NET version'
        required: true
        type: string
      dist:
        description: 'Distribution artifact'
        required: true
        type: string

jobs:
  e2e:
    runs-on: ${{ inputs.os }}
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: ${{ inputs.python-version }}
      - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      - name: Download dist
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: ${{ inputs.dist }}
          path: dist
      - name: Install pytest
        run: python -m pip install pytest
      - name: Install project
        run: pip install $(ls)
        working-directory: dist
      - name: Run end-to-end tests
        run: python -m pytest examples
